# Generated by Django 4.2.3 on 2023-07-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFixA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='appName',
            field=models.CharField(default='Null', max_length=20),
            preserve_default=False,
        ),
    ]
