# Generated by Django 4.2.3 on 2023-07-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppFixA', '0002_app_appname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('reportId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppFixA.app')),
            ],
            options={
                'verbose_name_plural': 'reports',
            },
        ),
    ]
